# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0400caf960695fa38870e6b18763aeeb"
name = "prueba-heroku"
handle = "prueba-heroku-2"
application_url = "https://prueba-heroku1.herokuapp.com"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://prueba-heroku1.herokuapp.com/auth/callback" ]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
